import { AnalysisConfig, StockData } from './types';

// Default configuration for stock analysis
export const defaultConfig: AnalysisConfig = {
  stockCriteria: {
    maxPrice: 15,
    minPrice: 0.1,
    sectors: [],
    excludeSectors: [],
    minMarketCap: 50000000, // $50M
  },
  analysisWeights: {
    growthPotential: 0.5,
    financialHealth: 0.3,
    pricePerformance: 0.2,
  },
  growthMetrics: {
    analystRecommendation: 0.25,
    upsidePotential: 0.35,
    revenueGrowth: 0.25,
    profitMargins: 0.15,
  },
  financialMetrics: {
    peRatio: 0.4,
    marketCap: 0.3,
    profitMargins: 0.3,
  },
  performanceMetrics: {
    yearlyPriceChange: 0.4,
    distanceFromHigh: 0.3,
    distanceFromLow: 0.3,
  },
  reportSettings: {
    topStocksCount: 5,
    includeAdditionalStocks: true,
    additionalStocksCount: 5,
    includeSectorAnalysis: true,
    includeInvestmentStrategies: true,
  },
};

// Mock data for development purposes
export const mockStocks: StockData[] = [
  {
    ticker: 'IONQ',
    companyName: 'IonQ, Inc.',
    currentPrice: 9.69,
    sector: 'Technology',
    industry: 'Computer Hardware',
    marketCap: 2000000000,
    peRatio: null,
    targetPrice: 15.50,
    recommendation: 'Buy',
    revenueGrowth: 0.9180,
    profitMargins: -0.25,
    yearlyPriceChangePct: 45.2,
    weekHigh52: 11.25,
    weekLow52: 4.35,
    description: 'IonQ is a leader in quantum computing, developing systems using trapped-ion technology.',
  },
  {
    ticker: 'SOUN',
    companyName: 'SoundHound AI, Inc.',
    currentPrice: 5.05,
    sector: 'Technology',
    industry: 'Software—Application',
    marketCap: 1500000000,
    peRatio: null,
    targetPrice: 7.60,
    recommendation: 'Strong Buy',
    revenueGrowth: 1.0150,
    profitMargins: -0.35,
    yearlyPriceChangePct: 62.8,
    weekHigh52: 6.85,
    weekLow52: 1.95,
    description: 'SoundHound AI develops voice AI solutions for businesses across various industries.',
  },
  {
    ticker: 'QUBT',
    companyName: 'Quantum Computing Inc.',
    currentPrice: 8.38,
    sector: 'Technology',
    industry: 'Computer Hardware',
    marketCap: 500000000,
    peRatio: null,
    targetPrice: 8.50,
    recommendation: 'Buy',
    revenueGrowth: 1.0200,
    profitMargins: -0.85,
    yearlyPriceChangePct: 28.5,
    weekHigh52: 9.45,
    weekLow52: 3.25,
    description: 'Quantum Computing Inc. focuses on quantum computing software and applications.',
  },
  {
    ticker: 'VTEX',
    companyName: 'VTEX',
    currentPrice: 5.05,
    sector: 'Technology',
    industry: 'Software—Application',
    marketCap: 950000000,
    peRatio: 18.5,
    targetPrice: 9.50,
    recommendation: 'Buy',
    revenueGrowth: 0.2580,
    profitMargins: 0.0529,
    yearlyPriceChangePct: 15.8,
    weekHigh52: 5.87,
    weekLow52: 3.42,
    description: 'VTEX provides a cloud-based e-commerce platform for enterprises in Latin America.',
  },
  {
    ticker: 'STLA',
    companyName: 'Stellantis N.V.',
    currentPrice: 12.64,
    sector: 'Consumer Cyclical',
    industry: 'Auto Manufacturers',
    marketCap: 39500000000,
    peRatio: 6.32,
    targetPrice: 15.96,
    recommendation: 'Buy',
    revenueGrowth: 0.0580,
    profitMargins: 0.0850,
    yearlyPriceChangePct: -8.5,
    weekHigh52: 18.97,
    weekLow52: 11.57,
    description: 'Stellantis is a multinational automotive manufacturer formed from the merger of PSA Group and Fiat Chrysler Automobiles.',
  },
  {
    ticker: 'LYFT',
    companyName: 'Lyft, Inc.',
    currentPrice: 13.85,
    sector: 'Technology',
    industry: 'Software—Application',
    marketCap: 5400000000,
    peRatio: null,
    targetPrice: 15.25,
    recommendation: 'Hold',
    revenueGrowth: 0.0850,
    profitMargins: -0.0320,
    yearlyPriceChangePct: 32.5,
    weekHigh52: 14.92,
    weekLow52: 8.05,
    description: 'Lyft operates a peer-to-peer marketplace for on-demand ridesharing in the United States and Canada.',
  },
  {
    ticker: 'BMBL',
    companyName: 'Bumble Inc.',
    currentPrice: 8.02,
    sector: 'Technology',
    industry: 'Software—Application',
    marketCap: 1100000000,
    peRatio: 35.8,
    targetPrice: 11.50,
    recommendation: 'Buy',
    revenueGrowth: 0.1250,
    profitMargins: 0.0420,
    yearlyPriceChangePct: -42.8,
    weekHigh52: 18.25,
    weekLow52: 7.85,
    description: 'Bumble operates online dating and social networking platforms that facilitate connections across dating, friendship, and professional networking.',
  },
  {
    ticker: 'SSYS',
    companyName: 'Stratasys Ltd.',
    currentPrice: 9.15,
    sector: 'Technology',
    industry: 'Computer Hardware',
    marketCap: 625000000,
    peRatio: null,
    targetPrice: 12.75,
    recommendation: 'Buy',
    revenueGrowth: -0.0580,
    profitMargins: -0.0950,
    yearlyPriceChangePct: -28.5,
    weekHigh52: 14.95,
    weekLow52: 8.25,
    description: 'Stratasys provides 3D printing and additive manufacturing solutions for industries including aerospace, automotive, healthcare, and consumer products.',
  },
  {
    ticker: 'PHUN',
    companyName: 'Phunware, Inc.',
    currentPrice: 5.73,
    sector: 'Technology',
    industry: 'Software—Application',
    marketCap: 85000000,
    peRatio: null,
    targetPrice: 8.50,
    recommendation: 'Buy',
    revenueGrowth: 0.3580,
    profitMargins: -0.7850,
    yearlyPriceChangePct: -35.8,
    weekHigh52: 12.85,
    weekLow52: 4.25,
    description: 'Phunware provides a fully-integrated enterprise cloud platform for mobile that provides products, solutions, data, and services for brands worldwide.',
  },
  {
    ticker: 'WEN',
    companyName: "Wendy's Company",
    currentPrice: 14.95,
    sector: 'Consumer Cyclical',
    industry: 'Restaurants',
    marketCap: 3100000000,
    peRatio: 19.8,
    targetPrice: 18.25,
    recommendation: 'Buy',
    revenueGrowth: 0.0580,
    profitMargins: 0.0850,
    yearlyPriceChangePct: -12.5,
    weekHigh52: 22.95,
    weekLow52: 14.25,
    description: "Wendy's is an American international fast food restaurant chain founded by Dave Thomas in 1969.",
  }
];
